storage: /verdaccio/storage/
plugins: /verdaccio/storage/
web:
  title: 私有 NPM 仓库
  pkgManagers:
    - npm
    - yarn
    - pnpm
  showFooter: false
auth:
  htpasswd:
    file: ./htpasswd
    algorithm: md5 # 这里选择 md5 作为加密算法
    max_users: -1 # 不允许自由注册
i18n:
  web: zh-CN

notify: # 1 修改发包的内网地址 2改写endpoint和对应手机号 3创建机器人安全选项加关键词: NPM
  method: POST
  headers: [{ "Content-Type": "application/json" }]
  endpoint: 钉钉机器人的webhooks地址
  content: '{"msgtype":"text", "at": {"atMobiles": [] }, "text":{"content":"NPM 发布新包：\n > 下载地址：http://你的内网ip:4873/{{name}}/-/{{name}}-{{#each versions}}{{version}}{{/each}}.tgz \n > 包名称：{{name}} \n > 版本号：{{#each versions}}{{version}}{{/each}} \n > 发布者：{{publisher.name}} "}}'
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
  yarn:
    url: https://registry.yarnpkg.com/
    timeout: 10s
  taobao:
    url: https://npmmirror.com/
    timeout: 10s

packages:
  "@*/*":
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs yarn taobao
  "**":
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs yarn taobao
middlewares:
  audit:
    enabled: true
listen: 0.0.0.0:4873
log: { type: stdout, format: pretty, level: http }
